version: '3'

services:
  pgsql:
    container_name: pgsql
    image: 'postgres:14'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=andrew
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q" ]
      retries: 3
      timeout: 5s

  app:
    container_name: app
    build: .
    volumes:
      - ./:/var/www/html:cached
    ports:
      - "1337:80"
    environment:
      PHP_IDE_CONFIG: serverName=coolest-server
    depends_on:
      - pgsql

volumes:
  pgsql-data: